// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Bi1aOey9qTvMGJO3DKAqmEGS5N0CaLA',
    appId: '1:285799025320:android:1ad76a5071c86d1619109d',
    messagingSenderId: '285799025320',
    projectId: 'shifo-app',
    storageBucket: 'shifo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2I636tlAIwx2v6WnOQVVJouX_Fb86wv4',
    appId: '1:285799025320:ios:7f016f113e5d21dc19109d',
    messagingSenderId: '285799025320',
    projectId: 'shifo-app',
    storageBucket: 'shifo-app.firebasestorage.app',
    iosBundleId: 'com.example.shifoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCpjtdS1PzRVHkYMO0E0fFG9e9SWohyCQ',
    appId: '1:285799025320:web:429694c43049441719109d',
    messagingSenderId: '285799025320',
    projectId: 'shifo-app',
    authDomain: 'shifo-app.firebaseapp.com',
    storageBucket: 'shifo-app.firebasestorage.app',
    measurementId: 'G-D160G8WDNV',
  );

}